### ISSUE TITLE
想问下您这边定制的删除功能具体实现的是什么效果？

### ISSUE THREAD

**Issue by Colstuwjx** [yinghonghui/yhhRedisShake#1]
如题。

**Comment by yinghonghui** [comment]
原集群和目标集群是一个，然后根据过了条件，就可以快速的删除目标缓存数据，回收内存。

**Comment by Colstuwjx** [comment]
没太理解，源和目标集群是同一个集群？然后根据过滤条件，每次同步都会把满足条件的 key 删掉吗

**Comment by yinghonghui** [comment]
有些场景需要对集群的目标内存进行大批量删除，
比如业务1客户端服务已经从A 集群切换到B集群，这时候A集群 业务1的数据已经是没有用的，需要回收对应内存。
把源集群，目标集群设置 A集群，通过一次全量同步，就能回收业务A的缓存内存

**Comment by Colstuwjx** [comment]
明白了，感谢！
